[package]
name = "phase2"
version = "0.2.2"
authors = ["Sean Bowe <ewillbefull@gmail.com>", "The Aleo Team <hello@aleo.org>"]
description = "Library for performing MPCs for creating zk-SNARK public parameters"
homepage = "https://github.com/AleoHQ/snark-setup"
repository = "https://github.com/AleoHQ/snark-setup"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
snark-utils = { path = "../snark-utils" }

snarkos-algorithms = { path = "../../snarkOS/algorithms" }
snarkos-models = { path = "../../snarkOS/models" }
snarkos-utilities = { path = "../../snarkOS/utilities" }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", package = "algebra", version = "0.1.0", features = ["parallel", "full"] }
zexe_groth16 = { git = "https://github.com/scipr-lab/zexe", package = "groth16", version = "0.1.0", features = ["parallel"] }
zexe_r1cs_core = { git = "https://github.com/scipr-lab/zexe", package = "r1cs-core", version = "0.1.0" }

byteorder = { version = "1.3.4" }
cfg-if = { version = "0.1.10" }
crossbeam = { version = "0.7" }
num_cpus = { version = "1" }
rand = { version = "0.7.3" }
rayon = { version = "1.3.0" }
tracing = { version = "0.1.13" }

[dev-dependencies]
powersoftau = { path = "../powersoftau" }
test-helpers = { path = "../test-helpers" }

snarkos-curves = { path = "../../snarkOS/curves" }

zexe_r1cs_std = { git = "https://github.com/scipr-lab/zexe", package = "r1cs-std", version = "0.1.0" }

tracing-subscriber = { version = "0.2.3" }
