[package]
name = "pairing_ce"

# Remember to change version string in README.md.
version = "0.17.0"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <jack@z.cash>",
    "Alex Vlasov <alex.m.vlasov@gmail.com>",
    "Alex Gluchowski <alex@gluchowski.net>"
]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/matter-labs/pairing"
repository = "https://github.com/matter-labs/pairing"
edition = "2018"

[dependencies]
rand = "0.4"
byteorder = "1"
#ff_ce = {version = "0.6", features = ["derive"] }
#ff_ce = { git = 'https://github.com/matter-labs/ff', features = ["derive"], branch = "gpu"}
ff_ce = { path = '../ff', features = ["derive", "derive_serde"]}
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
hex = "0.3.2"

[features]
unstable-features = ["expose-arith"]
expose-arith = []
default = []
