[package]
name = "bellman-demo"
version = "0.1.0"

[dependencies]
rand = "0.4"
hex = "0.3.2"
time = "0.1"
num-bigint = "0.2"
ff = { version = "0.4", features = ["derive"] }
bellman = { path = "../.." }
pairing = { git = 'https://github.com/matterinc/pairing' }
