[package]
name = "phase1"
version = "0.3.0"
authors = ["Sean Bowe", "Alex Vlasov", "The Aleo Team <hello@aleo.org>"]
description = "Communal zk-SNARK MPC for Public Parameters"
homepage = "https://github.com/AleoHQ/aleo-setup"
repository = "https://github.com/AleoHQ/aleo-setup"
license = "MIT/Apache-2.0"
edition = "2018"

[[bench]]
name = "phase1"
harness = false

[dependencies]
setup-utils = { path = "../setup-utils", features = ["parallel"] }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0", features = ["parallel", "derive"] }
zexe_algebra_core = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra-core", version = "0.1.0", optional = true, features = ["parallel", "derive"] }

itertools = { version = "0.8.0" }
rand = { version = "0.7" }
rayon = { version = "1.3.0" }
tracing = { version = "0.1.17" }
tracing-subscriber = { version = "0.2.3" }

[dev-dependencies]
phase1 = { path = "./", features = ["testing"] }

snarkos-curves = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-curves", default-features = false }
snarkos-models = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-models", default-features = false }
snarkos-utilities = { git = "ssh://git@github.com/AleoHQ/snarkOS.git", package = "snarkos-utilities" }

zexe_algebra = { git = "https://github.com/scipr-lab/zexe", rev = "b24eda5", package = "algebra", version = "0.1.0", features = ["parallel", "full", "derive"] }

anyhow = { version = "1.0.31" }
criterion = { version = "0.3" }
num-traits = { version = "0.2.12" }
rusty-hook = { version = "0.11.2" }

[features]
default = []
testing = ["zexe_algebra_core"]
