[package]
name = "phase1"
version = "0.3.0"
authors = ["Sean Bowe", "Alex Vlasov", "The Aleo Team <hello@aleo.org>"]
description = "Core logic for Phase 1"
homepage = "https://github.com/AleoHQ/aleo-setup"
repository = "https://github.com/AleoHQ/aleo-setup"
license = "MIT/Apache-2.0"
edition = "2018"

[[bench]]
name = "phase1"
harness = false
required-features = ["benchmark"]

[dependencies]
setup-utils = { path = "../setup-utils", default-features = false }

cfg-if = { version = "0.1.10" }
criterion = { version = "0.3", optional = true }
itertools = { version = "0.9.0" }
rand = { version = "0.7" }
rayon = { version = "1.4.1", optional = true }
tracing = { version = "0.1.21" }
derivative = { version = "2", features = [ "use_core" ] }
snarkos-profiler = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-profiler" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
phase1 = { path = "./", features = ["testing"] }

snarkos-algorithms = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-algorithms", default-features = false }
snarkos-curves = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-curves", default-features = false }
snarkos-errors = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-errors", default-features = false }
snarkos-gadgets = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-gadgets", default-features = false }
snarkos-marlin = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-marlin", default-features = false }
snarkos-models = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-models", default-features = false }
snarkos-objects = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-objects", default-features = false }
snarkos-polycommit = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-polycommit", default-features = false }
snarkos-posw = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-posw", default-features = false }
snarkos-utilities = { git = "https://github.com/AleoHQ/snarkOS", rev = "801bf76", package = "snarkos-utilities", default-features = false }

anyhow = { version = "1.0.37" }
blake2 = { version = "0.8", default-features = false }
num-traits = { version = "0.2.12" }
rusty-hook = { version = "0.11.2" }

[features]
default = ["cli"]
cli = ["parallel", "setup-utils/cli"]
parallel = ["rayon", "setup-utils/parallel"]
wasm = ["setup-utils/wasm"]

benchmark = ["criterion"]
testing = ["parallel", "snarkos-profiler/print-trace"]

[[test]]
name = "aleo_compatibility"
path = "tests/aleo_compatibility.rs"
required-features = ["phase1/testing"]

[[test]]
name = "marlin"
path = "tests/marlin.rs"
required-features = ["phase1/testing", "cli"]

