[package]
name = "phase1-coordinator"
version = "0.3.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Coordinator implementation of Phase 1"
homepage = "https://github.com/AleoHQ/aleo-setup"
repository = "https://github.com/AleoHQ/aleo-setup"
license = "MIT/Apache-2.0"
edition = "2018"

[[bin]]
name = "phase1-coordinator"
path = "src/main.rs"

[dependencies]
phase1 = { path = "../phase1" }

curl = { version = "0.4.33" }
lazy_static = { version = "1.4.0" }
once_cell = { version = "1.4.1" }
rayon = { version = "1.4.0" }
rocket = { version = "0.4.5" }
rocket_contrib = { version = "0.4", features = ["json"] }
schemars = { version = "0.8.0-alpha-4", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde-aux = { version = "0.6" }
serde_json = { version = "1.0" }
tokio = { version = "0.2.22", features = ["sync"] }
tracing = { version = "0.1.19" }
tracing-subscriber = { version = "0.2" }
url = { version = "1.0" }
url_serde = { version = "0.2.0" }
